### ISSUE TITLE
external-properties-file property

### ISSUE THREAD

**Issue by gc4rella** [openbaton/integration-tests#2]
What is this? 

| external-properties-file   | If you want to use another file for fetching the properties. It is already preset to */etc/openbaton/integration-test/integration-test.properties*. If it does not exist it will not be used. |

usually you have to pass the configuration file while starting the application.

**Comment by marcellom** [comment]
When I and Lorenzo wrote this project, it was a simple JAVA application, without Spring support that does what you say. So, I used this approach that allows you to have an external property file. Actually, I see Spring dependencies in the build.gradle but I think this project uses only JAVA.
